# Related: https://github.com/docker/compose/issues/3435
---
version: '2.1'
services:
  some:
    # It MUST be on single line https://github.com/docker/compose/issues/4189#issuecomment-338254508 (https://github.com/docker/compose/issues/4670)
    # And it can *NOT* be used in docker-compose itself, f.e. For PORT or volumes specification. See @issue https://github.com/docker/compose/issues/3435
    # But see workaround.bash…
    env_file: .env.$DOCKER_ENV
    image: nginx
    volumes:
      - ${DOCKER_MOUNT_DIR}:/usr/share/nginx/html:ro
    ports:
      - "$DOCKER_PORT:80"
#    command: bash -c 'env | grep DOCKER'